<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><Compile Include="../src/Terrain.cs" Link="Terrain.cs"/><Compile Include="../src/ExampleLocation.cs" Link="ExampleLocation.cs"/><Compile Include="../src/MapLayers.cs" Link="MapLayers.cs"/><PackageReference Include="NetTopologySuite" Version="2.6.0" /></ItemGroup>
</Project>
